#!/bin/sh

# Adapted from https://golang.org/misc/git/pre-commit
# Keep in sync with "make fmt".

gofiles=$(cd server && gofmt -l .)
webfiles=$(pnpm exec prettier -l --cache --cache-strategy metadata .)
[ -z "$gofiles" -a -z "$webfiles" ] && exit 0

echo >&2 "Misformatted files:"
for fn in $gofiles $webfiles; do
  echo >&2 "  $fn"
done
echo >&2
echo >&2 "Please run: make fmt"

exit 1
