export interface Country {
  name: string
  code: string
  flag: string
}

// Extracted from frontend/ChapterList.vue's allCountries list.
export const COUNTRIES: Country[] = [
  { name: 'Ascension Island', code: 'AC', flag: '🇦🇨' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫' },
  { name: 'Antigua & Barbuda', code: 'AG', flag: '🇦🇬' },
  { name: 'Anguilla', code: 'AI', flag: '🇦🇮' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴' },
  { name: 'Antarctica', code: 'AQ', flag: '🇦🇶' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { name: 'American Samoa', code: 'AS', flag: '🇦🇸' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺' },
  { name: 'Aruba', code: 'AW', flag: '🇦🇼' },
  { name: 'Åland Islands', code: 'AX', flag: '🇦🇽' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿' },
  { name: 'Bosnia & Herzegovina', code: 'BA', flag: '🇧🇦' },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯' },
  { name: 'St. Barthélemy', code: 'BL', flag: '🇧🇱' },
  { name: 'Bermuda', code: 'BM', flag: '🇧🇲' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴' },
  { name: 'Caribbean Netherlands', code: 'BQ', flag: '🇧🇶' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹' },
  { name: 'Bouvet Island', code: 'BV', flag: '🇧🇻' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', flag: '🇨🇨' },
  { name: 'Congo - Kinshasa', code: 'CD', flag: '🇨🇩' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫' },
  { name: 'Congo - Brazzaville', code: 'CG', flag: '🇨🇬' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { name: 'Côte d’Ivoire', code: 'CI', flag: '🇨🇮' },
  { name: 'Cook Islands', code: 'CK', flag: '🇨🇰' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲' },
  { name: 'China', code: 'CN', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { name: 'Clipperton Island', code: 'CP', flag: '🇨🇵' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺' },
  { name: 'Cape Verde', code: 'CV', flag: '🇨🇻' },
  { name: 'Curaçao', code: 'CW', flag: '🇨🇼' },
  { name: 'Christmas Island', code: 'CX', flag: '🇨🇽' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾' },
  { name: 'Czechia', code: 'CZ', flag: '🇨🇿' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪' },
  { name: 'Diego Garcia', code: 'DG', flag: '🇩🇬' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿' },
  { name: 'Ceuta & Melilla', code: 'EA', flag: '🇪🇦' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨' },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { name: 'Western Sahara', code: 'EH', flag: '🇪🇭' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹' },
  { name: 'European Union', code: 'EU', flag: '🇪🇺' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯' },
  { name: 'Falkland Islands', code: 'FK', flag: '🇫🇰' },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲' },
  { name: 'Faroe Islands', code: 'FO', flag: '🇫🇴' },
  { name: 'France', code: 'FR', flag: '🇫🇷' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪' },
  { name: 'French Guiana', code: 'GF', flag: '🇬🇫' },
  { name: 'Guernsey', code: 'GG', flag: '🇬🇬' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { name: 'Gibraltar', code: 'GI', flag: '🇬🇮' },
  { name: 'Greenland', code: 'GL', flag: '🇬🇱' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳' },
  { name: 'Guadeloupe', code: 'GP', flag: '🇬🇵' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷' },
  { name: 'South Georgia & South Sandwich Islands', code: 'GS', flag: '🇬🇸' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹' },
  { name: 'Guam', code: 'GU', flag: '🇬🇺' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾' },
  { name: 'Hong Kong SAR China', code: 'HK', flag: '🇭🇰' },
  { name: 'Heard & McDonald Islands', code: 'HM', flag: '🇭🇲' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺' },
  { name: 'Canary Islands', code: 'IC', flag: '🇮🇨' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱' },
  { name: 'Isle of Man', code: 'IM', flag: '🇮🇲' },
  { name: 'India', code: 'IN', flag: '🇮🇳' },
  { name: 'British Indian Ocean Territory', code: 'IO', flag: '🇮🇴' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹' },
  { name: 'Jersey', code: 'JE', flag: '🇯🇪' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲' },
  { name: 'St. Kitts & Nevis', code: 'KN', flag: '🇰🇳' },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼' },
  { name: 'Cayman Islands', code: 'KY', flag: '🇰🇾' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧' },
  { name: 'St. Lucia', code: 'LC', flag: '🇱🇨' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪' },
  { name: 'St. Martin', code: 'MF', flag: '🇲🇫' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱' },
  { name: 'Myanmar (Burma)', code: 'MM', flag: '🇲🇲' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳' },
  { name: 'Macao SAR China', code: 'MO', flag: '🇲🇴' },
  { name: 'Northern Mariana Islands', code: 'MP', flag: '🇲🇵' },
  { name: 'Martinique', code: 'MQ', flag: '🇲🇶' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷' },
  { name: 'Montserrat', code: 'MS', flag: '🇲🇸' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦' },
  { name: 'New Caledonia', code: 'NC', flag: '🇳🇨' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪' },
  { name: 'Norfolk Island', code: 'NF', flag: '🇳🇫' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷' },
  { name: 'Niue', code: 'NU', flag: '🇳🇺' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪' },
  { name: 'French Polynesia', code: 'PF', flag: '🇵🇫' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱' },
  { name: 'St. Pierre & Miquelon', code: 'PM', flag: '🇵🇲' },
  { name: 'Pitcairn Islands', code: 'PN', flag: '🇵🇳' },
  { name: 'Puerto Rico', code: 'PR', flag: '🇵🇷' },
  { name: 'Palestinian Territories', code: 'PS', flag: '🇵🇸' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { name: 'Palau', code: 'PW', flag: '🇵🇼' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦' },
  { name: 'Réunion', code: 'RE', flag: '🇷🇪' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { name: 'St. Helena', code: 'SH', flag: '🇸🇭' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮' },
  { name: 'Svalbard & Jan Mayen', code: 'SJ', flag: '🇸🇯' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷' },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸' },
  { name: 'São Tomé & Príncipe', code: 'ST', flag: '🇸🇹' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻' },
  { name: 'Sint Maarten', code: 'SX', flag: '🇸🇽' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿' },
  { name: 'Tristan da Cunha', code: 'TA', flag: '🇹🇦' },
  { name: 'Turks & Caicos Islands', code: 'TC', flag: '🇹🇨' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩' },
  { name: 'French Southern Territories', code: 'TF', flag: '🇹🇫' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯' },
  { name: 'Tokelau', code: 'TK', flag: '🇹🇰' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { name: 'Trinidad & Tobago', code: 'TT', flag: '🇹🇹' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬' },
  { name: 'U.S. Outlying Islands', code: 'UM', flag: '🇺🇲' },
  { name: 'United Nations', code: 'UN', flag: '🇺🇳' },
  { name: 'United States', code: 'US', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦' },
  { name: 'St. Vincent & Grenadines', code: 'VC', flag: '🇻🇨' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { name: 'British Virgin Islands', code: 'VG', flag: '🇻🇬' },
  { name: 'U.S. Virgin Islands', code: 'VI', flag: '🇻🇮' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺' },
  { name: 'Wallis & Futuna', code: 'WF', flag: '🇼🇫' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸' },
  { name: 'Kosovo', code: 'XK', flag: '🇽🇰' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪' },
  { name: 'Mayotte', code: 'YT', flag: '🇾🇹' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼' },
]
