import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

// Generated by shadcn. See https://dev.to/ramunarasinga/cn-utility-function-in-shadcn-uiui-3c4k
// for an explanation. Used to conditionally merge tailwind classnames
// while avoiding style conflicts. Classnames that appear later take precedence.
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
