language: generic
dist: bionic

env:
  - GOFLAGS=-mod=readonly GOPROXY=https://proxy.golang.org

services:
  - docker
  - mysql

before_install:
  - nvm use stable
  - node --version
  - npm --version
  - eval "$(gimme stable)"
  - go version

install:
  - npm ci
  - go mod download

before_script:
  - mysql -u root -e "CREATE USER adb_user@localhost IDENTIFIED BY 'adbpassword';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* to adb_user@localhost;"
  - mysql -u root -e "CREATE DATABASE adb_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE DATABASE adb_test_db CHARACTER SET utf8 COLLATE utf8_general_ci;"

script:
  - ./hooks/pre-commit
  - go test github.com/dxe/adb/...
  - docker build -t mdempsky/adb .

deploy:
  provider: script
  script: bash push-to-docker-hub.sh
  on:
    branch: master
