name: dxe-adb

services:
  mysql:
    # Keep version in sync with:
    # * server/src/testdb/mysql_container.go
    # * .github/workflows/main.yml
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localdev
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: {}
