import { buildActivistsHref } from '@/app/(authed)/activists/activists-href'
import type { ParsedActivistQueryParams } from '@/app/(authed)/activists/search-params'
import type { NavbarData } from '@/lib/nav-access'

const activistsHref = (query: Partial<ParsedActivistQueryParams>) =>
  `/v2${buildActivistsHref(query)}`

const daysAgo = (days: number) => ({
  mode: 'relative' as const,
  daysOffset: -days,
})

export const navbarData: NavbarData = {
  items: [
    {
      label: 'Attendance',
      roleRequired: ['attendance'],
      visibleForNonSFBay: true,
      items: [
        {
          label: 'New Event',
          href: '/v2/events/new',
          page: 'NewEvent_beta',
        },
        {
          label: 'All Events',
          href: '/v2/events',
          page: 'EventList_beta',
          separatorBelow: true,
        },
        {
          label: 'New Coaching',
          href: '/v2/coachings/new',
          page: 'NewConnection_beta',
          roleRequired: ['organizer'],
          visibleForNonSFBay: false,
        },
        {
          label: 'All Coachings',
          href: '/v2/coachings',
          page: 'ConnectionsList_beta',
          roleRequired: ['organizer'],
          visibleForNonSFBay: false,
        },
      ],
    },
    {
      label: 'Groups',
      roleRequired: ['organizer'],
      visibleForNonSFBay: false,
      items: [
        {
          label: 'Geo-Circles',
          href: '/v2/circles?type=geo',
          page: 'CirclesList_beta',
        },
        {
          label: 'Interest Circles',
          href: '/v2/circles?type=interest',
          page: 'CirclesList_beta',
        },
        {
          label: 'Working Groups',
          href: '/v2/working-groups',
          page: 'WorkingGroupList_beta',
        },
      ],
    },
    {
      label: 'Prospects',
      roleRequired: ['organizer'],
      visibleForNonSFBay: false,
      items: [
        {
          label: 'Community Prospects',
          href: activistsHref({
            lastEvent: { lt: daysAgo(360), orNull: true },
            totalInteractions: { lt: 1 },
            activistLevel: { mode: 'include', values: ['Supporter'] },
            source: {
              include: [
                'form',
                'dxe-signup',
                'arc-signup',
                'petition',
                'eventbrite',
              ],
              exclude: ['application'],
            },
            columns: [
              'pronouns',
              'email',
              'phone',
              'total_events',
              'first_event',
              'first_event_name',
              'last_event',
              'assigned_to_name',
              'followup_date',
              'total_interactions',
              'last_interaction_date',
              'source',
              'interest_date',
              'notes',
            ],
            sort: [{ column: 'interest_date', desc: true }],
          }),
          page: 'ActivistListV2',
        },
        {
          label: 'Chapter Member Prospects',
          href: activistsHref({
            activistLevel: {
              mode: 'exclude',
              values: ['Chapter Member', 'Organizer'],
            },
            prospect: 'chapterMember',
            columns: [
              'pronouns',
              'email',
              'phone',
              'activist_level',
              'total_events',
              'last_event',
              'mpi',
              'training0',
              'consent_quiz',
              'dev_application_date',
              'dev_application_type',
              'prospect_chapter_member',
              'cm_first_email',
              'cm_approval_email',
              'notes',
            ],
            sort: [{ column: 'dev_application_date', desc: true }],
          }),
          page: 'ActivistListV2',
        },
        {
          label: 'Organizer Prospects',
          href: activistsHref({
            prospect: 'organizer',
            activistLevel: { mode: 'exclude', values: ['Organizer'] },
            columns: [
              'pronouns',
              'activist_level',
              'total_events',
              'last_event',
              'mpi',
              'training0',
              'training1',
              'training4',
              'training5',
              'training6',
              'dev_application_date',
              'dev_application_type',
              'prospect_organizer',
              'dev_quiz',
              'dev_interest',
              'notes',
            ],
            sort: [{ column: 'dev_application_date', desc: true }],
          }),
          page: 'ActivistListV2',
        },
        {
          label: 'My follow-ups',
          href: activistsHref({
            assignedTo: 'me',
            followups: 'due',
            columns: [
              'pronouns',
              'email',
              'phone',
              'total_events',
              'first_event',
              'first_event_name',
              'last_event',
              'assigned_to_name',
              'followup_date',
              'total_interactions',
              'last_interaction_date',
              'source',
              'interest_date',
              'notes',
            ],
            sort: [{ column: 'interest_date', desc: true }],
          }),
          page: 'ActivistListV2',
        },
        {
          label: 'Interest Form Generator',
          href: '/v2/interest/generator',
          page: 'InterestFormGenerator',
          visibleForNonSFBay: false,
        },
      ],
    },
    {
      label: 'Activists',
      roleRequired: ['organizer'],
      visibleForNonSFBay: true,
      items: [
        {
          label: 'Chapter Members',
          href: activistsHref({
            columns: [
              'preferred_name',
              'pronouns',
              'email',
              'phone',
              'activist_level',
              'total_events',
              'months_since_last_action',
              'mpp_requirements',
              'mpi',
              'geo_circles',
              'cm_approval_email',
              'vision_wall',
              'voting_agreement',
              'notes',
              'hiatus',
            ],
            activistLevel: {
              mode: 'include',
              values: ['Chapter Member', 'Organizer'],
            },
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: false,
        },
        {
          label: 'Organizers',
          href: activistsHref({
            columns: [
              'pronouns',
              'mpi',
              'training1',
              'training4',
              'training5',
              'training6',
              'dev_quiz',
              'connector',
              'last_connection',
              'notes',
            ],
            activistLevel: { mode: 'include', values: ['Organizer'] },
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: false,
        },
        {
          label: 'Leaderboard',
          href: activistsHref({
            columns: [
              'pronouns',
              'activist_level',
              'total_events',
              'first_event',
              'first_event_name',
              'last_event',
              'last_event_name',
              'total_points',
              'mpi',
            ],
            lastEvent: { gte: daysAgo(30) },
            sort: [{ column: 'total_points', desc: true }],
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: false,
        },
        {
          label: 'All Activists',
          href: activistsHref({
            columns: [
              'pronouns',
              'email',
              'phone',
              'activist_level',
              'location',
              'city',
              'total_events',
              'last_event',
            ],
            sort: [{ column: 'last_event', desc: true }],
            totalEvents: { gte: 1 },
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: true,
        },
        {
          label: 'New Activists',
          href: activistsHref({
            columns: [
              'pronouns',
              'email',
              'phone',
              'facebook',
              'activist_level',
              'total_events',
              'first_event',
              'last_event',
              'mpi',
              'source',
            ],
            lastEvent: { gte: daysAgo(180) },
            totalEvents: { lt: 4 },
            sort: [{ column: 'last_event', desc: true }],
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: true,
        },
        {
          label: 'New Activists Pending Workshop',
          href: activistsHref({
            firstEvent: { gte: daysAgo(180) },
            activistLevel: { mode: 'include', values: ['Supporter'] },
            training: { include: [], exclude: ['training0'] },
            columns: [
              'activist_level',
              'first_event',
              'last_event',
              'training0',
              'source',
            ],
            sort: [{ column: 'last_event', desc: true }],
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: false,
        },
        {
          label: 'New Activists Recently Inactive',
          href: activistsHref({
            lastEvent: { gte: daysAgo(180), lt: daysAgo(14) },
            totalEvents: { lt: 4 },
            columns: [
              'activist_level',
              'total_events',
              'first_event',
              'first_event_name',
              'last_event',
              'last_event_name',
              'source',
            ],
            sort: [{ column: 'last_event', desc: true }],
          }),
          page: 'ActivistListV2',
          visibleForNonSFBay: true,
        },
      ],
    },
    {
      label: 'Admin',
      roleRequired: ['admin', 'intl_coordinator'],
      visibleForNonSFBay: true,
      items: [
        {
          label: 'Chapters',
          href: '/v2/chapters',
          page: 'ChaptersList_beta',
          roleRequired: ['admin', 'intl_coordinator'],
        },
        {
          label: 'International Organizers',
          href: '/v2/intl/organizers',
          page: 'IntlOrganizers',
          roleRequired: ['admin', 'intl_coordinator'],
        },
        {
          label: 'Users',
          href: '/v2/users',
          page: 'UserList',
          roleRequired: ['admin'],
        },
        {
          label: 'Facebook Events',
          href: '/v2/external-events',
          page: 'FacebookEvents_beta',
          roleRequired: ['admin'],
        },
        {
          label: 'Configuration',
          href: '/v2/config',
          page: 'Config',
          roleRequired: ['admin'],
        },
      ],
    },
  ],
}
