CREATE TABLE IF NOT EXISTS debug_sql_queries(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(80) NOT NULL,
  sql_query MEDIUMTEXT NOT NULL,
  explain_analyze_result MEDIUMTEXT NOT NULL
);
