import { Suspense } from 'react'
import { ContentWrapper } from '@/app/content-wrapper'
import { InterestForm } from './interest-form'

// Public (unauthenticated) "Interest" sign-up form. Ported from
// frontend/FormInterest.vue, which is served at the Vue route `/interest`.
// Behavior (title, description, which fields are shown) is parameterized by
// URL query params generated by the "Interest Form Generator" at
// /interest/generator (frontend-v2/src/app/(authed)/interest/generator).
export default function InterestPage() {
  return (
    <ContentWrapper size="sm" className="gap-6">
      <Suspense>
        <InterestForm />
      </Suspense>
    </ContentWrapper>
  )
}
